package map;
// Generated 30-abr-2020 16:47:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Aviso generated by hbm2java
 */
public class Aviso  implements java.io.Serializable {


     private Integer idAviso;
     private Expediente expediente;
     private Date fecha;
     private String email;
     private String descripcion;

    public Aviso() {
    }

    public Aviso(Expediente expediente, Date fecha, String email, String descripcion) {
       this.expediente = expediente;
       this.fecha = fecha;
       this.email = email;
       this.descripcion = descripcion;
    }
   
    public Integer getIdAviso() {
        return this.idAviso;
    }
    
    public void setIdAviso(Integer idAviso) {
        this.idAviso = idAviso;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


