package map;
// Generated 24-abr-2020 13:48:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String dni;
     private String nombreCompleto;
     private Date fechaNacimiento;
     private String sexo;
     private String situacionFamiliar;
     private String situacionLaboral;
     private Set expedientes = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String dni, String nombreCompleto, Date fechaNacimiento, String sexo, String situacionFamiliar, String situacionLaboral) {
        this.dni = dni;
        this.nombreCompleto = nombreCompleto;
        this.fechaNacimiento = fechaNacimiento;
        this.sexo = sexo;
        this.situacionFamiliar = situacionFamiliar;
        this.situacionLaboral = situacionLaboral;
    }
    public Cliente(String dni, String nombreCompleto, Date fechaNacimiento, String sexo, String situacionFamiliar, String situacionLaboral, Set expedientes) {
       this.dni = dni;
       this.nombreCompleto = nombreCompleto;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
       this.situacionFamiliar = situacionFamiliar;
       this.situacionLaboral = situacionLaboral;
       this.expedientes = expedientes;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getSituacionFamiliar() {
        return this.situacionFamiliar;
    }
    
    public void setSituacionFamiliar(String situacionFamiliar) {
        this.situacionFamiliar = situacionFamiliar;
    }
    public String getSituacionLaboral() {
        return this.situacionLaboral;
    }
    
    public void setSituacionLaboral(String situacionLaboral) {
        this.situacionLaboral = situacionLaboral;
    }
    public Set getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set expedientes) {
        this.expedientes = expedientes;
    }




}


