package map;
// Generated 31-mar-2020 13:59:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private String matricula;
     private String marca;
     private String modelo;
     private String color;
     private String numeroBastidor;
     private String aseguradora;
     private String numeroPoliza;
     private Set datosincidentesesForCoche = new HashSet(0);
     private Set datosincidentesesForCocheContrario = new HashSet(0);

    public Coches() {
    }

	
    public Coches(String matricula, String aseguradora, String numeroPoliza) {
        this.matricula = matricula;
        this.aseguradora = aseguradora;
        this.numeroPoliza = numeroPoliza;
    }
    public Coches(String matricula, String marca, String modelo, String color, String numeroBastidor, String aseguradora, String numeroPoliza, Set datosincidentesesForCoche, Set datosincidentesesForCocheContrario) {
       this.matricula = matricula;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.numeroBastidor = numeroBastidor;
       this.aseguradora = aseguradora;
       this.numeroPoliza = numeroPoliza;
       this.datosincidentesesForCoche = datosincidentesesForCoche;
       this.datosincidentesesForCocheContrario = datosincidentesesForCocheContrario;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getNumeroBastidor() {
        return this.numeroBastidor;
    }
    
    public void setNumeroBastidor(String numeroBastidor) {
        this.numeroBastidor = numeroBastidor;
    }
    public String getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(String aseguradora) {
        this.aseguradora = aseguradora;
    }
    public String getNumeroPoliza() {
        return this.numeroPoliza;
    }
    
    public void setNumeroPoliza(String numeroPoliza) {
        this.numeroPoliza = numeroPoliza;
    }
    public Set getDatosincidentesesForCoche() {
        return this.datosincidentesesForCoche;
    }
    
    public void setDatosincidentesesForCoche(Set datosincidentesesForCoche) {
        this.datosincidentesesForCoche = datosincidentesesForCoche;
    }
    public Set getDatosincidentesesForCocheContrario() {
        return this.datosincidentesesForCocheContrario;
    }
    
    public void setDatosincidentesesForCocheContrario(Set datosincidentesesForCocheContrario) {
        this.datosincidentesesForCocheContrario = datosincidentesesForCocheContrario;
    }




}


