package map;
// Generated 31-mar-2020 13:59:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Datosincidentes generated by hbm2java
 */
public class Datosincidentes  implements java.io.Serializable {


     private Integer codigo;
     private Coches cochesByCoche;
     private Coches cochesByCocheContrario;
     private Date fechaHora;
     private String lugar;
     private String defensa;
     private String parte;
     private String enviadoPor;
     private Set expedienteses = new HashSet(0);

    public Datosincidentes() {
    }

	
    public Datosincidentes(Coches cochesByCoche, Date fechaHora, String lugar, String enviadoPor) {
        this.cochesByCoche = cochesByCoche;
        this.fechaHora = fechaHora;
        this.lugar = lugar;
        this.enviadoPor = enviadoPor;
    }
    public Datosincidentes(Coches cochesByCoche, Coches cochesByCocheContrario, Date fechaHora, String lugar, String defensa, String parte, String enviadoPor, Set expedienteses) {
       this.cochesByCoche = cochesByCoche;
       this.cochesByCocheContrario = cochesByCocheContrario;
       this.fechaHora = fechaHora;
       this.lugar = lugar;
       this.defensa = defensa;
       this.parte = parte;
       this.enviadoPor = enviadoPor;
       this.expedienteses = expedienteses;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Coches getCochesByCoche() {
        return this.cochesByCoche;
    }
    
    public void setCochesByCoche(Coches cochesByCoche) {
        this.cochesByCoche = cochesByCoche;
    }
    public Coches getCochesByCocheContrario() {
        return this.cochesByCocheContrario;
    }
    
    public void setCochesByCocheContrario(Coches cochesByCocheContrario) {
        this.cochesByCocheContrario = cochesByCocheContrario;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getDefensa() {
        return this.defensa;
    }
    
    public void setDefensa(String defensa) {
        this.defensa = defensa;
    }
    public String getParte() {
        return this.parte;
    }
    
    public void setParte(String parte) {
        this.parte = parte;
    }
    public String getEnviadoPor() {
        return this.enviadoPor;
    }
    
    public void setEnviadoPor(String enviadoPor) {
        this.enviadoPor = enviadoPor;
    }
    public Set getExpedienteses() {
        return this.expedienteses;
    }
    
    public void setExpedienteses(Set expedienteses) {
        this.expedienteses = expedienteses;
    }




}


