package map;
// Generated 31-mar-2020 13:59:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Datospersonales generated by hbm2java
 */
public class Datospersonales  implements java.io.Serializable {


     private String dni;
     private String nombreCompleto;
     private Date fechaNacimiento;
     private String situacionFamiliar;
     private String situacionLaboral;
     private Set expedienteses = new HashSet(0);

    public Datospersonales() {
    }

	
    public Datospersonales(String dni, String nombreCompleto, Date fechaNacimiento, String situacionFamiliar, String situacionLaboral) {
        this.dni = dni;
        this.nombreCompleto = nombreCompleto;
        this.fechaNacimiento = fechaNacimiento;
        this.situacionFamiliar = situacionFamiliar;
        this.situacionLaboral = situacionLaboral;
    }
    public Datospersonales(String dni, String nombreCompleto, Date fechaNacimiento, String situacionFamiliar, String situacionLaboral, Set expedienteses) {
       this.dni = dni;
       this.nombreCompleto = nombreCompleto;
       this.fechaNacimiento = fechaNacimiento;
       this.situacionFamiliar = situacionFamiliar;
       this.situacionLaboral = situacionLaboral;
       this.expedienteses = expedienteses;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getSituacionFamiliar() {
        return this.situacionFamiliar;
    }
    
    public void setSituacionFamiliar(String situacionFamiliar) {
        this.situacionFamiliar = situacionFamiliar;
    }
    public String getSituacionLaboral() {
        return this.situacionLaboral;
    }
    
    public void setSituacionLaboral(String situacionLaboral) {
        this.situacionLaboral = situacionLaboral;
    }
    public Set getExpedienteses() {
        return this.expedienteses;
    }
    
    public void setExpedienteses(Set expedienteses) {
        this.expedienteses = expedienteses;
    }




}


