package map;
// Generated 26-may-2020 18:05:19 by Hibernate Tools 4.3.1



/**
 * DocumentoId generated by hbm2java
 */
public class DocumentoId  implements java.io.Serializable {


     private int codExpediente;
     private String nombre;

    public DocumentoId() {
    }

    public DocumentoId(int codExpediente, String nombre) {
       this.codExpediente = codExpediente;
       this.nombre = nombre;
    }
   
    public int getCodExpediente() {
        return this.codExpediente;
    }
    
    public void setCodExpediente(int codExpediente) {
        this.codExpediente = codExpediente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocumentoId) ) return false;
		 DocumentoId castOther = ( DocumentoId ) other; 
         
		 return (this.getCodExpediente()==castOther.getCodExpediente())
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodExpediente();
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         return result;
   }   


}


