package map;
// Generated 31-mar-2020 13:59:39 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Expedientes generated by hbm2java
 */
public class Expedientes  implements java.io.Serializable {


     private Integer codigo;
     private Datosincidentes datosincidentes;
     private Datospersonales datospersonales;
     private Date fechaCreacion;

    public Expedientes() {
    }

    public Expedientes(Datosincidentes datosincidentes, Datospersonales datospersonales, Date fechaCreacion) {
       this.datosincidentes = datosincidentes;
       this.datospersonales = datospersonales;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Datosincidentes getDatosincidentes() {
        return this.datosincidentes;
    }
    
    public void setDatosincidentes(Datosincidentes datosincidentes) {
        this.datosincidentes = datosincidentes;
    }
    public Datospersonales getDatospersonales() {
        return this.datospersonales;
    }
    
    public void setDatospersonales(Datospersonales datospersonales) {
        this.datospersonales = datospersonales;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


