package map;
// Generated 05-jun-2020 17:28:59 by Hibernate Tools 4.3.1



/**
 * Smtp generated by hbm2java
 */
public class Smtp  implements java.io.Serializable {


     private String host;
     private String puerto;
     private String email;
     private String contrasena;
     private String opcion;

    public Smtp() {
    }

    public Smtp(String host, String puerto, String email, String contrasena, String opcion) {
       this.host = host;
       this.puerto = puerto;
       this.email = email;
       this.contrasena = contrasena;
       this.opcion = opcion;
    }
   
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public String getPuerto() {
        return this.puerto;
    }
    
    public void setPuerto(String puerto) {
        this.puerto = puerto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }




}


