package map;
// Generated 26-may-2020 18:05:19 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String nombre;
     private String contrasena;

    public Usuarios() {
    }

    public Usuarios(String nombre, String contrasena) {
       this.nombre = nombre;
       this.contrasena = contrasena;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


