package map;
// Generated 22-may-2020 18:32:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String matricula;
     private String marca;
     private String modelo;
     private String color;
     private String numeroBastidor;
     private String aseguradora;
     private String numeroPoliza;
     private String rol;
     private Set expedientes = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String matricula, String marca, String modelo, String color, String numeroBastidor, String aseguradora, String numeroPoliza, String rol) {
        this.matricula = matricula;
        this.marca = marca;
        this.modelo = modelo;
        this.color = color;
        this.numeroBastidor = numeroBastidor;
        this.aseguradora = aseguradora;
        this.numeroPoliza = numeroPoliza;
        this.rol = rol;
    }
    public Vehiculo(String matricula, String marca, String modelo, String color, String numeroBastidor, String aseguradora, String numeroPoliza, String rol, Set expedientes) {
       this.matricula = matricula;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.numeroBastidor = numeroBastidor;
       this.aseguradora = aseguradora;
       this.numeroPoliza = numeroPoliza;
       this.rol = rol;
       this.expedientes = expedientes;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getNumeroBastidor() {
        return this.numeroBastidor;
    }
    
    public void setNumeroBastidor(String numeroBastidor) {
        this.numeroBastidor = numeroBastidor;
    }
    public String getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(String aseguradora) {
        this.aseguradora = aseguradora;
    }
    public String getNumeroPoliza() {
        return this.numeroPoliza;
    }
    
    public void setNumeroPoliza(String numeroPoliza) {
        this.numeroPoliza = numeroPoliza;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set expedientes) {
        this.expedientes = expedientes;
    }




}


