-- MySQL Script generated by MySQL Workbench
-- Wed Apr 22 17:48:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema geslexbd
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `dni` VARCHAR(9) NULL DEFAULT NULL,
  `nombre_completo` VARCHAR(70) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` ENUM('Mujer', 'Hombre') NOT NULL,
  `situacion_familiar` ENUM('Soltero/a', 'Casado/a', 'Divorciado/a', 'Viudo/a') NOT NULL,
  `situacion_laboral` ENUM('Empleado/a', 'Desempleado/a') NOT NULL,
  PRIMARY KEY (`dni`));


-- -----------------------------------------------------
-- Table `mydb`.`letrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`letrado` (
  `dni_letrado` VARCHAR(9) NULL DEFAULT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `colegio` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(40) NOT NULL,
  `telefono` INT(9) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`dni_letrado`));


-- -----------------------------------------------------
-- Table `mydb`.`procurador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`procurador` (
  `dni_procurador` VARCHAR(9) NULL DEFAULT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `direccion` VARCHAR(40) NOT NULL,
  `telefono` INT(9) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`dni_procurador`));


-- -----------------------------------------------------
-- Table `mydb`.`preito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preito` (
  `dni_perito` VARCHAR(9) NULL DEFAULT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `direccion` VARCHAR(40) NOT NULL,
  `provincia` VARCHAR(50) NOT NULL,
  `telefono` INT(9) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`dni_perito`));


-- -----------------------------------------------------
-- Table `mydb`.`expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expediente` (
  `codigo` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NOT NULL,
  `fecha_cierre` DATE NULL DEFAULT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `dni_letrado` VARCHAR(9) NOT NULL,
  `dni_procurador` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX (`dni` ASC) VISIBLE,
  INDEX (`dni_letrado` ASC) VISIBLE,
  INDEX (`dni_procurador` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`dni`)
    REFERENCES `mydb`.`cliente` (`dni`),
  CONSTRAINT ``
    FOREIGN KEY (`dni_letrado`)
    REFERENCES `mydb`.`letrado` (`dni_letrado`),
  CONSTRAINT ``
    FOREIGN KEY (`dni_procurador`)
    REFERENCES `mydb`.`procurador` (`dni_procurador`));


-- -----------------------------------------------------
-- Table `mydb`.`incidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidente` (
  `codigo_expediente` INT NULL DEFAULT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `lugar` VARCHAR(30) NOT NULL,
  `defensa` VARCHAR(250) NULL DEFAULT NULL,
  `parte` ENUM('Amistoso', 'Asestado') NOT NULL,
  `enviado_por` VARCHAR(70) NOT NULL,
  `fallecidos` ENUM('Si', 'No') NOT NULL,
  PRIMARY KEY (`codigo_expediente`),
  CONSTRAINT ``
    FOREIGN KEY (`codigo_expediente`)
    REFERENCES `mydb`.`expediente` (`codigo`));


-- -----------------------------------------------------
-- Table `mydb`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehiculo` (
  `matricula` VARCHAR(7) NULL DEFAULT NULL,
  `marca` VARCHAR(15) NOT NULL,
  `modelo` VARCHAR(15) NOT NULL,
  `color` VARCHAR(15) NOT NULL,
  `numero_bastidor` VARCHAR(20) NOT NULL,
  `aseguradora` VARCHAR(20) NOT NULL,
  `numero_poliza` VARCHAR(20) NOT NULL,
  `codigo_expediente` INT NULL DEFAULT NULL,
  `rol` ENUM('Cliente', 'Implicado/a') NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX (`codigo_expediente` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`codigo_expediente`)
    REFERENCES `mydb`.`expediente` (`codigo`));


-- -----------------------------------------------------
-- Table `mydb`.`sentencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sentencia` (
  `cod_expediente` INT NULL DEFAULT NULL,
  `titulo` VARCHAR(40) NULL DEFAULT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `pdf` BLOB NOT NULL,
  PRIMARY KEY (`cod_expediente`, `titulo`),
  CONSTRAINT ``
    FOREIGN KEY (`cod_expediente`)
    REFERENCES `mydb`.`expediente` (`codigo`));


-- -----------------------------------------------------
-- Table `mydb`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento` (
  `cod_expediente` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `pdf` BLOB NOT NULL,
  `aportado_por` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`cod_expediente`, `nombre`),
  CONSTRAINT ``
    FOREIGN KEY (`cod_expediente`)
    REFERENCES `mydb`.`expediente` (`codigo`));


-- -----------------------------------------------------
-- Table `mydb`.`hoja_encargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hoja_encargo` (
  `cod_expediente` INT NULL DEFAULT NULL,
  `hoja` BLOB NOT NULL,
  PRIMARY KEY (`cod_expediente`),
  CONSTRAINT ``
    FOREIGN KEY (`cod_expediente`)
    REFERENCES `mydb`.`expediente` (`codigo`));


-- -----------------------------------------------------
-- Table `mydb`.`aviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aviso` (
  `id_aviso` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `cod_expediente` INT NOT NULL,
  PRIMARY KEY (`id_aviso`),
  INDEX (`cod_expediente` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`cod_expediente`)
    REFERENCES `mydb`.`expediente` (`codigo`));


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `nombre` VARCHAR(20) NULL DEFAULT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`nombre`));


-- -----------------------------------------------------
-- Table `mydb`.`expediente_has_preito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`expediente_has_preito` (
  `expediente_codigo` INT NOT NULL,
  `preito_dni_perito` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`expediente_codigo`, `preito_dni_perito`),
  INDEX `fk_expediente_has_preito_preito1_idx` (`preito_dni_perito` ASC) VISIBLE,
  INDEX `fk_expediente_has_preito_expediente1_idx` (`expediente_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_expediente_has_preito_expediente1`
    FOREIGN KEY (`expediente_codigo`)
    REFERENCES `mydb`.`expediente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expediente_has_preito_preito1`
    FOREIGN KEY (`preito_dni_perito`)
    REFERENCES `mydb`.`preito` (`dni_perito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
